create table if not exists holdings (
  id bigint generated by default as identity primary key,
  ticker text not null,
  shares numeric(12, 4) not null check (shares > 0),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists goal (
  id bigint primary key,
  monthly_target numeric(12, 2) not null default 0,
  weekly_investment numeric(12, 2) not null default 0
);

create table if not exists dividend_history (
  id bigint generated by default as identity primary key,
  month date not null unique,
  total_monthly_income numeric(12, 2) not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

insert into goal (id, monthly_target, weekly_investment)
values (1, 0, 0)
on conflict (id) do nothing;

